// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID         string             `json:"id"`
	FirstName  pgtype.Text        `json:"first_name"`
	MiddleName pgtype.Text        `json:"middle_name"`
	LastName   pgtype.Text        `json:"last_name"`
	Grp        pgtype.Text        `json:"grp"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AccountGlobalRole struct {
	AccountID string `json:"account_id"`
	RoleKey   string `json:"role_key"`
}

type Approval struct {
	ProcessID   string             `json:"process_id"`
	StageKey    string             `json:"stage_key"`
	ByAccountID string             `json:"by_account_id"`
	ByRole      string             `json:"by_role"`
	Decision    string             `json:"decision"`
	Comment     string             `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Identity struct {
	ID           string             `json:"id"`
	AccountID    string             `json:"account_id"`
	Provider     string             `json:"provider"`
	Subject      string             `json:"subject"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	RefreshToken pgtype.Text        `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Outbox struct {
	ID          int64              `json:"id"`
	Topic       string             `json:"topic"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type Process struct {
	ID           string             `json:"id"`
	ProjectID    string             `json:"project_id"`
	TemplateKey  string             `json:"template_key"`
	Name         string             `json:"name"`
	CurrentStage string             `json:"current_stage"`
	State        string             `json:"state"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ProcessMember struct {
	ProcessID string `json:"process_id"`
	AccountID string `json:"account_id"`
	RoleKey   string `json:"role_key"`
}

type Project struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Theme     pgtype.Text        `json:"theme"`
	Descr     pgtype.Text        `json:"descr"`
	CreatedBy string             `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectMember struct {
	ProjectID string `json:"project_id"`
	AccountID string `json:"account_id"`
	RoleKey   string `json:"role_key"`
}
