// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: outbox.sql

package sqlc

import (
	"context"
)

const appendOutbox = `-- name: AppendOutbox :exec
INSERT INTO outbox (topic, payload)
VALUES ($1, $2)
`

type AppendOutboxParams struct {
	Topic   string `json:"topic"`
	Payload []byte `json:"payload"`
}

func (q *Queries) AppendOutbox(ctx context.Context, arg AppendOutboxParams) error {
	_, err := q.db.Exec(ctx, appendOutbox, arg.Topic, arg.Payload)
	return err
}
